### ISSUE TITLE
Having troubles after react-native upgrade to version 0.69.6

### ISSUE THREAD

**Issue by lunacy42** [Nozbe/WatermelonDB#1426]
I have upgraded my project to a newer react-native version (0.69.6) and I get a few errors. 

The imports of withObservables don't work anymore, so I had to change the path from:
```
import withObservables from "@nozbe/watermelondb"
```
to the exact path:
```
import withObservables from "@nozbe/watermelondb/node_modules/@nozbe/with-observables/src"
```
That works now, but the next problem is coming up:
The useDatabase hooks seems to not work anymore. I get this error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
My question is: how to fix the above problem, and: Which is the latest react-native version to run watermelondb with?

**Comment by maratumba** [comment]
I've been having the same issue too and going through the steps in the [provided link](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react), I noticed that watermelondb installs a different version of react than the one currently in use (see below).

From react docs:
> If you see more than one React, you’ll need to figure out why this happens and fix your dependency tree. For example, maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency). Until that library is fixed, [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) is one possible workaround.

```sh
npm ls react
app@0.0.1 /Users/gulyamani/devel/naughtsReactNative
├─┬ @nozbe/watermelondb@0.24.0
│ └─┬ @nozbe/with-observables@1.4.0
│   └── react@17.0.2 <= Here
├─┬ react-native-paper@5.1.3
│ ├─┬ @callstack/react-theme-provider@3.0.8
│ │ └── react@18.2.0 deduped
│ ├── react@18.2.0 deduped
│ └─┬ use-event-callback@0.1.0
│   └── react@18.2.0 deduped
├─┬ react-native-safe-area-context@4.4.1
│ └── react@18.2.0 deduped
├─┬ react-native@0.71.0
│ ├─┬ react-shallow-renderer@16.15.0
│ │ └── react@18.2.0 deduped
│ ├── react@18.2.0 deduped
│ └─┬ use-sync-external-store@1.2.0
│   └── react@18.2.0 deduped
├─┬ react-test-renderer@18.2.0
│ └── react@18.2.0 deduped
└── react@18.2.0
```

**Comment by radex** [comment]
This doesn't sound right, peer dependencies is just a warning, it shouldn't be able to force old react to be downloaded

**Comment by nicolasgeronimorodi** [comment]
![capturaNPMLS](https://user-images.githubusercontent.com/84360079/216740359-fd0323fa-4364-423c-84f3-26102fa0b090.png)

I´ve been having the same issue.  Can´t get the useDatabase hook to work. It throws invalid hook call; one of the reasons being duplicated react install or compatibilty issue.

Any help would be highly appreciated.

**Comment by radex** [comment]
Fixed in `@nozbe/with-observables@1.5.0-2` / `@nozbe/watermelondb@0.26.0-9`

**Comment by nicolasgeronimorodi** [comment]
> Fixed in `@nozbe/with-observables@1.5.0-2` / `@nozbe/watermelondb@0.26.0-9`

I just installed again using npm install nozbe/watermelondb and I still get the error every time the useDatabase hook is called. What do you suggest?

**Comment by radex** [comment]
@nicolasgeronimorodi did you verify that the version I mentioned is the one that was installed?

**Comment by nicolasgeronimorodi** [comment]
> @nicolasgeronimorodi I installed using the registry. Any ideas on how to install that specific version?
