### ISSUE TITLE
Compilation error for RN 0.71

### ISSUE THREAD

**Issue by johnf** [Nozbe/WatermelonDB#1469]
In RN 0.71 the JSCRFuntime files have been moved into their own folder, see https://github.com/facebook/react-native/commit/f3bf4d02abf8d22bada8bfcee7ccfbd3bb524750

This means you get the following error
```
dir/JSLockPerfHack.cpp.o.d -o CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o -c '/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp'
  /home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp:2:10: fatal error: 'jsi/JSCRuntime.h' file not found
  #include <jsi/JSCRuntime.h>
           ^~~~~~~~~~~~~~~~~~
```
A quick patch is
```diff
diff --git a/node_modules/@nozbe/watermelondb/WatermelonDB.podspec b/node_modules/@nozbe/watermelondb/WatermelonDB.podspec
index 1f3af50..5216cde 100644
--- a/node_modules/@nozbe/watermelondb/WatermelonDB.podspec
+++ b/node_modules/@nozbe/watermelondb/WatermelonDB.podspec
@@ -19,4 +19,5 @@ Pod::Spec.new do |s|
   s.compiler_flags = '-Os'
   s.dependency "React"
   s.dependency "React-jsi"
+  s.dependency "React-jsc"
 end
diff --git a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
index b920271..47ed5a9 100644
--- a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
+++ b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
@@ -1,5 +1,5 @@
 #include "JSLockPerfHack.h"
-#include <jsi/JSCRuntime.h>
+#include <jsc/JSCRuntime.h>
 
 using namespace facebook;
 
diff --git a/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB.xcodeproj/project.pbxproj b/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB.xcodeproj/project.pbxproj
index cabaf36..d911757 100644
--- a/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB.xcodeproj/project.pbxproj
+++ b/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB.xcodeproj/project.pbxproj
@@ -398,6 +398,8 @@
 					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-Core/**",
 					"$(SRCROOT)/../../../../../ios/Pods/Headers/Public/React-jsi/**",
 					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-jsi/**",
+					"$(SRCROOT)/../../../../../ios/Pods/Headers/Public/React-jsc/**",
+					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-jsc/**",
 				);
 				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
 				LD_RUNPATH_SEARCH_PATHS = (
@@ -452,6 +454,8 @@
 					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-Core/**",
 					"$(SRCROOT)/../../../../../ios/Pods/Headers/Public/React-jsi/**",
 					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-jsi/**",
+					"$(SRCROOT)/../../../../../ios/Pods/Headers/Public/React-jsc/**",
+					"$(SRCROOT)/../../../../../../native/ios/Pods/Headers/Public/React-jsc/**",
 				);
 				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
 				LD_RUNPATH_SEARCH_PATHS = (
diff --git a/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.mm b/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.mm
index a5b592c..dcab616 100644
--- a/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.mm
+++ b/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/JSLockPerfHack.mm
@@ -1,7 +1,7 @@
 #import "JSLockPerfHack.h"
 #import <UIKit/UIKit.h>
 #import <JavaScriptCore/JavaScriptCore.h>
-#import <jsi/JSCRuntime.h>
+#import "JSCRuntime.h" // I think we need quotes here because React-jsc doesn't have a jsc subdirectory???
 #import <objc/runtime.h>
 #import <objc/message.h>
 
```
You also need to add the following to the Podfile
```Podfile
pod 'React-jsc', :path => '../node_modules/react-native/ReactCommon/jsc', :modular_headers => true
```

I'd create a PR but I'm not sure of the best way to support post and pre 0.71

**Comment by kuldeepworkid** [comment]
This is not working. i have just created a fresh project have RN version 0.71
i have my patches at path **MyProject/patches/@nozbe+watermelondb+0.24.0.patch**
i have run this command _npx patch-package @nozbe/watermelondb_ , copy & pasted your above given code, but its still showing the same error in both android and ios.

**Comment by LuizCristino** [comment]
Tested on Android and debug worked fine

**Comment by radex** [comment]
I'll look into these issues soon, hopefully on Friday.

**Comment by KrisLau** [comment]
@radex Please also look at https://github.com/Nozbe/WatermelonDB/pull/1249

**Comment by kuldeepworkid** [comment]
> also gradle plugin version has error too
> 
> ```
> * What went wrong:
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':nozbe_watermelondb' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
> ```

android/build.gradle
change the **kotlinVersion = '1.3.50'** to **kotlinVersion = '1.6.0'**

**Comment by radex** [comment]
@johnf et al: Please check 🍉 0.25 release - I believe this should fix the compilation issue, can you confirm?

**Comment by johnf** [comment]
@radex Looks ok on iOS but still broken on Android due to the include in https://github.com/Nozbe/WatermelonDB/blob/master/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':watermelondb-jsi:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/.cxx/Debug/2b34443c/arm64-v8a'
  [1/10] Building CXX object CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o
  FAILED: CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o 
  /home/johnf/opt/Android/SDK/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android23 --gcc-toolchain=/home/johnf/opt/Android/SDK/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/johnf/opt/Android/SDK/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Dwatermelondb_jsi_EXPORTS -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../shared -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/@nozbe/sqlite/sqlite-amalgamation-3360000 -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/@nozbe/simdjson/src -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/react-native/React -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/react-native/React/Base -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/react-native/ReactCommon -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../node_modules/react-native/ReactCommon/jsi -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../sqlite/sqlite-amalgamation-3360000 -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../simdjson/src -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../react-native/React -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../react-native/React/Base -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../react-native/ReactCommon -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../react-native/ReactCommon/jsi -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../../../native/node_modules/react-native/React -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../../../native/node_modules/react-native/React/Base -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../../../native/node_modules/react-native/ReactCommon -I/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/../../../../../../../../../native/node_modules/react-native/ReactCommon/jsi -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -Os -fPIC -MD -MT CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o -MF CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o.d -o CMakeFiles/watermelondb-jsi.dir/JSLockPerfHack.cpp.o -c '/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp'
  /home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp:2:10: fatal error: 'jsi/JSCRuntime.h' file not found
  #include <jsi/JSCRuntime.h>
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
  [2/10] Building CXX object CMakeFiles/watermelondb-jsi.dir/JSIInstaller.cpp.o
  [3/10] Building CXX object CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp.o
  [4/10] Building CXX object 'CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/shared/Sqlite.cpp.o'
  [5/10] Building CXX object CMakeFiles/watermelondb-jsi.dir/DatabasePlatformAndroid.cpp.o
  [6/10] Building CXX object 'CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/@nozbe/simdjson/src/simdjson.cpp.o'
  [7/10] Building CXX object 'CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/shared/DatabaseInstallation.cpp.o'
  [8/10] Building C object 'CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/@nozbe/sqlite/sqlite-amalgamation-3360000/sqlite3.c.o'
  [9/10] Building CXX object 'CMakeFiles/watermelondb-jsi.dir/home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/shared/Database.cpp.o'
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /home/johnf/opt/Android/SDK/cmake/3.18.1/bin/ninja \
        -C \
        /home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi/.cxx/Debug/2b34443c/arm64-v8a \
        watermelondb-jsi
    from /home/johnf/work/gladly/mobile/node_modules/@nozbe/watermelondb/native/android-jsi
```

**Comment by radex** [comment]
Oops. I'm not even sure why this import is there, it's not useful for anything.

Can you verify on your side that removing this import fixes the build?

**Comment by LuizCristino** [comment]
> Oops. I'm not even sure why this import is there, it's not useful for anything.
> 
> Can you verify on your side that removing this import fixes the build?

Here it worked after commenting `#include <jsi/JSCRuntime.h>`

Also I'm using RN 0.71.1

**Comment by johnf** [comment]
Works for me too

**Comment by radex** [comment]
I've released 0.25.1 with the Android fix. Sorry, I missed this one. Hopefully it's good now.

**Comment by 1mike12** [comment]
> change the kotlinVersion = '1.3.50' to kotlinVersion = '1.6.0'

For those that aren't sure like me how to do this:

```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.6.0"
    }
    ...
 ```
